/**
 * The landing page shows what the analysis produced, and goes on showing it.
 *
 * Story 34 asks a Signer to judge whether Redline's claims are checkable by looking at
 * one. Ticket 17 served that with an illustration, which is honest and weaker: the
 * product's whole claim is that its output is checkable rather than plausible-sounding,
 * and a drawing of the output cannot be checked at all. So the page now sets
 * `lib/landing/sample-analysis.ts`, generated by running the real `analyze()` seam over a
 * fixture contract, and this file is what makes that claim true rather than asserted.
 *
 * Three things are checked, and they are the three ways the claim could quietly stop
 * being true.
 *
 * **The committed file is what the analysis produces.** The analysis is run again here
 * and compared with what is committed, value by value and then byte for byte against what
 * the generator would write today. A change in how a flag is titled, ranked, explained or
 * cut out of the document fails here until `npm run sample` has been run — which is the
 * ticket's last criterion: a stale demonstration is a defect, not a picture worth keeping.
 *
 * **Every citation on it verifies.** Held to the product's own standard rather than a
 * looser one for marketing: `citationVerifies` is the function that stands between a
 * model's quote and a Signer, and it is the function the page's quotes are put through.
 *
 * **The page says what it is.** The sample contract is named on the page as a fixture, and
 * the illustration's own labelling is gone rather than left contradicting real output.
 *
 * The live model is unreachable from this build, so the sample was produced with the
 * fixture-backed stub gateway (`tests/support/stub-model.ts`). Everything downstream of
 * the gateway is the product's own — the citation check, the severity derivation, the
 * wording — and the page says as much in its own words rather than implying a live model
 * wrote it.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";

import Home from "@/app/page";
import { citationVerifies, createCitationVerifier } from "@/lib/analysis/citation";
import { CHECKLIST_ENTRIES } from "@/lib/analysis/clauses";
import { checklistEntryName, severityWord } from "@/lib/analysis/wording";
import { LANDING_SAMPLE } from "@/lib/landing/sample-analysis";

import {
  SAMPLE_FIXTURE,
  SAMPLE_MODULE_PATH,
  buildLandingSample,
  renderSampleModule,
} from "../scripts/landing-sample";
import { loadFixture } from "./support/fixtures";

const fixture = loadFixture(SAMPLE_FIXTURE);

/** The rendered text with tags and entities removed, as `tests/positioning.test.ts` does. */
function readable(html: string): string {
  return html
    .replace(/<[^>]*>/g, " ")
    .replace(/&#x27;|&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&nbsp;/g, " ")
    .replace(/&#x([0-9a-fA-F]+);/g, (_match, code) => String.fromCodePoint(parseInt(code, 16)));
}

/** The landing page as it renders, with whitespace collapsed so quotes can be found in it. */
function landingPageText(): string {
  return readable(renderToStaticMarkup(createElement(Home))).replace(/\s+/g, " ");
}

/** One string, with whitespace collapsed the same way, so the two can be compared. */
function flat(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

describe("the worked example on the landing page", () => {
  it("is what the analysis produces from the fixture, not a copy that has drifted", async () => {
    // Value equality first, because it is the claim that matters and it names the field
    // that moved when it fails.
    expect(LANDING_SAMPLE).toEqual(await buildLandingSample());
  });

  it("is committed exactly as the generator writes it, so it can be reproduced", async () => {
    const path = fileURLToPath(new URL(`../${SAMPLE_MODULE_PATH}`, import.meta.url));
    const committed = readFileSync(path, "utf8").replace(/\r\n/g, "\n");
    expect(committed).toBe(renderSampleModule(await buildLandingSample()));
  });

  it("was produced by the analysis seam over a fixture, and says which one", () => {
    expect(LANDING_SAMPLE.fixture).toBe(SAMPLE_FIXTURE);
    expect(LANDING_SAMPLE.producedBy).toBe("fixture-stub");
    expect(LANDING_SAMPLE.flags.length).toBeGreaterThan(0);

    // Nothing on it is written for the page. Every title, severity word and cleared-list
    // name comes from the analysis's own vocabulary, so a flag worded on the landing page
    // and worded differently on the review screen is not representable.
    for (const flag of LANDING_SAMPLE.flags) {
      expect(flag.severityWord, flag.id).toBe(severityWord(flag.severity));
    }
    for (const entry of LANDING_SAMPLE.cleared) {
      expect(entry.name, entry.entry).toBe(checklistEntryName(entry.entry));
      expect(CHECKLIST_ENTRIES, entry.entry).toContain(entry.entry);
    }
    expect(LANDING_SAMPLE.checklistTotal).toBe(CHECKLIST_ENTRIES.length);
  });

  it("quotes sentences the sample contract contains, on the product's own standard", () => {
    // `docs/adr/0001` held to on a marketing page, using the same function the product
    // uses. Paraphrase fails here, reformatting fails here, half a sentence fails here.
    const verifier = createCitationVerifier(fixture.text);

    for (const flag of LANDING_SAMPLE.flags) {
      expect(citationVerifies(fixture.text, flag.sourceSentence), flag.id).toBe(true);
      expect(verifier.verified(flag.sourceSentence), flag.id).toBe(flag.sourceSentence);
    }

    const jurisdiction = LANDING_SAMPLE.jurisdiction;
    if (jurisdiction !== null) {
      // The law the reading was made under is a claim about the document too, and it
      // carries the sentence it was read from (`docs/adr/0007`).
      expect(citationVerifies(fixture.text, jurisdiction.sourceSentence)).toBe(true);
    }
  });

  it("sets the contract's own words around each mark, not a retyping of them", () => {
    // The blocks are quotations as much as the citations are. Each one has to appear in
    // the fixture exactly as it is set, and the marked run inside it has to be the flag's
    // own sentence.
    for (const clause of LANDING_SAMPLE.clauses) {
      const whole = clause.spans.map((span) => span.text).join("");
      expect(fixture.text, whole.slice(0, 40)).toContain(whole);
      if (clause.heading !== null) expect(fixture.text).toContain(clause.heading);

      for (const span of clause.spans) {
        if (span.flagId === null) continue;
        const flag = LANDING_SAMPLE.flags.find((candidate) => candidate.id === span.flagId);
        expect(flag, span.flagId ?? "").toBeDefined();
        expect(span.text).toBe(flag?.sourceSentence);
      }
    }

    // Every flag is marked somewhere on the sheet, so the ranked index cannot list a
    // finding the contract below it does not carry a mark for.
    const marked = LANDING_SAMPLE.clauses.flatMap((clause) => clause.flagIds);
    expect([...marked].sort()).toEqual(LANDING_SAMPLE.flags.map((flag) => flag.id).sort());
  });
});

describe("what the landing page puts in front of a Signer", () => {
  const text = landingPageText();

  it("renders the analysis's own findings, and the sentences they came from", () => {
    for (const flag of LANDING_SAMPLE.flags) {
      expect(text, flag.id).toContain(flat(flag.title));
      expect(text, flag.id).toContain(flat(flag.sourceSentence));
    }
    // Only the open mark's explanation renders; the rest open on selection.
    expect(text).toContain(flat(LANDING_SAMPLE.flags[0].cost));
    for (const entry of LANDING_SAMPLE.cleared) {
      expect(text, entry.entry).toContain(flat(entry.name));
    }
  });

  it("names the sample contract as a fixture and claims nothing about a live model", () => {
    expect(text).toContain(SAMPLE_FIXTURE);
    expect(text).toMatch(/a test file from this repo's corpus/i);
    expect(text).toMatch(/Nobody's real document went into it/i);
    expect(text).toMatch(
      /the stand-in the test suite works against, so nothing here tells you how the live model reads a contract/i
    );
    // The illustration's own labelling from ticket 17, which said the marks were drawn
    // rather than produced. Left in place it would contradict the real output beside it.
    expect(text).not.toMatch(/The marks illustrate how Redline reads a document/i);
    expect(text).not.toMatch(/No real contract was analysed/i);
    expect(text).not.toMatch(/written for this page/i);
  });

  it("makes none of the three claims ticket 16 found the illustration making", () => {
    // 1. The sample payment clause states its standard — the client's sole and absolute
    //    discretion — so the page may not say the contract is silent about it. The
    //    analysis writes two different sentences for a stated standard and a missing one
    //    (`lib/analysis/wording.ts`), and the page now says whichever one it wrote.
    expect(text).not.toMatch(/nothing in the contract says what good enough means/i);
    expect(text).toContain("a matter of their own satisfaction");

    // 2. The sample non-compete does state that nothing is paid for the restriction, so
    //    saying so is reporting the document. What the illustration did was assert
    //    silence as a negative fact, which is what the product refuses. Whichever of the
    //    two sentences appears, it is the one the analysis wrote for this clause.
    const nonCompete = LANDING_SAMPLE.flags.find((flag) => flag.clauseType === "non-compete");
    expect(nonCompete).toBeDefined();
    expect(text).toContain(flat(nonCompete?.title ?? ""));

    // 3. The cleared list is the product's own checklist, by name, rather than a list of
    //    clause headings Redline has no checklist entry for.
    const named = new Set(LANDING_SAMPLE.cleared.map((entry) => entry.entry));
    for (const entry of named) expect(CHECKLIST_ENTRIES).toContain(entry);
    for (const retired of ["Invoice due date", "Expenses", "Revisions", "Governing law"]) {
      expect(text, retired).not.toContain(retired);
    }
    // And it counts itself honestly: four cleared out of eight checked, said in the
    // legend, rather than claiming every clause in the contract was named.
    expect(text).toContain(
      `${LANDING_SAMPLE.cleared.length} of ${LANDING_SAMPLE.checklistTotal} came back clean`
    );
    expect(text).not.toMatch(/Redline names every clause it examined/i);
  });

  it("keeps the path from a mark to its sentence reachable and announced", () => {
    // `PRODUCT.md`'s accessibility consequence: a citation a Signer cannot navigate to is
    // a citation they cannot check. Both halves of every pair are buttons, each margin
    // mark points at the id of the sentence it marks, and severity ships on three
    // channels rather than on colour.
    const html = renderToStaticMarkup(createElement(Home));
    for (const flag of LANDING_SAMPLE.flags) {
      expect(html, flag.id).toContain(`aria-controls="sentence-${flag.id}"`);
      expect(html, flag.id).toContain(`id="sentence-${flag.id}"`);
      expect(html, flag.id).toContain(`severity, ${flag.severity} of 4`);
      expect(readable(html), flag.id).toContain(flag.severityWord);
    }
    expect(html).toContain('aria-pressed="true"');
  });
});
