"use client";

/**
 * The landing page: what Redline does, shown by doing it.
 *
 * The demonstration on this page is not an illustration of the product's output. It is
 * the output — `lib/landing/sample-analysis.ts`, generated by running the real `analyze()`
 * seam over a contract from the test corpus, with every citation checked the way the
 * product checks one (`scripts/landing-sample.ts`). The page reads that file and sets it;
 * it writes no findings of its own, which is why nothing here can say something about the
 * sample contract that the analysis did not say.
 *
 * Generated ahead of time because this page is prerendered and calls no model
 * (`.impeccable/surfaces/app-page-tsx.md`). `tests/landing-sample.test.ts` runs the
 * analysis again and fails when the committed file and the analysis disagree, so the page
 * shows the product as it is now rather than a picture of an older one.
 *
 * The form is `DESIGN.md`'s and the direction contract's: the Paired Mark Rule, severity
 * on three channels, the leader rule at 1024px and above and nowhere else.
 */

import { useCallback, useEffect, useRef, useState } from "react";

import {
  LABEL,
  Masthead,
  ProofMark,
  SeverityMeter,
  STAMP,
  TrimMarks,
  markFor,
} from "@/app/(app)/_components/galley";
import { LANDING_SAMPLE } from "@/lib/landing/sample-analysis";

const { fixture, jurisdiction, flags, clauses, cleared, checklistTotal } = LANDING_SAMPLE;

const WHAT_YOU_GET: [string, string][] = [
  [
    "Risky clauses, ranked worst first.",
    "Each flag quotes the sentence it came from. If it cannot show you that sentence, Redline does not show the flag.",
  ],
  [
    "A counter-offer drafted for every flag.",
    "Wording you can paste straight into a reply to your client, written to go out as it stands.",
  ],
  [
    "Questions answered from the document itself.",
    "Ask what a clause means, or what the contract does not cover. Where the document is silent, Redline says so.",
  ],
];

/**
 * Where the marked contract came from, said before it is read.
 *
 * Two claims, and both of them are the kind this product is built to be careful about.
 * The contract is a fixture from this repo's own corpus and is named as one, because a
 * demonstration implying a real client's document would fabricate the sort of proof
 * `PRODUCT.md` says does not exist. And the run behind it used the stand-in gateway the
 * test suite runs on rather than the live model, so the page claims the reading as
 * Redline's own and claims nothing at all about how the live model reads a contract.
 */
const WHERE_THIS_CAME_FROM =
  `The contract below is a test file from this repo's corpus, ${fixture}, written to carry ` +
  "the terms freelance agreements go wrong on. Nobody's real document went into it. What " +
  "is marked on it is what Redline gave back when it read that file, down to the sentence " +
  "under each mark. The run used the stand-in the test suite works against, so nothing " +
  "here tells you how the live model reads a contract.";

/** The law the reading was made under, declared in the legend (`docs/adr/0007`). */
const LAW_READ_UNDER =
  jurisdiction === null
    ? "No governing law named"
    : `Read under the law of ${jurisdiction.name}`;

export default function Home() {
  const [selected, setSelected] = useState(flags[0]?.id ?? "");
  const galleyRef = useRef<HTMLDivElement>(null);
  const markRefs = useRef<Record<string, HTMLButtonElement | null>>({});
  const sentenceRefs = useRef<Record<string, HTMLSpanElement | null>>({});
  const [leader, setLeader] = useState<{ points: string; w: number; h: number } | null>(
    null,
  );

  const measure = useCallback(() => {
    const galley = galleyRef.current;
    const mark = markRefs.current[selected];
    const sentence = sentenceRefs.current[selected];
    if (!galley || !mark || !sentence) return setLeader(null);
    if (!window.matchMedia("(min-width: 1024px)").matches) return setLeader(null);

    const g = galley.getBoundingClientRect();
    const m = mark.getBoundingClientRect();
    const rects = sentence.getClientRects();
    const head = rects[0];
    if (!head) return setLeader(null);

    // A proof mark ties to its line. A wrapped span's first rect ends at the wrap
    // point with nothing after it, so the leader can land there. On a single-line
    // span it would cross whatever follows, so it stops at the column edge instead.
    const column = sentence.closest("p")?.getBoundingClientRect();
    const anchor = rects.length > 1 ? head.right : (column?.right ?? head.right);
    const x1 = m.left - g.left - 12;
    const y1 = m.top - g.top + 17;
    const x2 = anchor - g.left + 7;
    const y2 = head.top - g.top + head.height / 2;
    const elbow = x2 + (x1 - x2) * 0.45;

    setLeader({
      points: `${x1},${y1} ${elbow},${y1} ${elbow},${y2} ${x2},${y2}`,
      w: g.width,
      h: g.height,
    });
  }, [selected]);

  useEffect(() => {
    measure();
    const onResize = () => measure();
    window.addEventListener("resize", onResize);
    const observer = new ResizeObserver(onResize);
    if (galleyRef.current) observer.observe(galleyRef.current);
    document.fonts?.ready.then(onResize).catch(() => {});
    return () => {
      window.removeEventListener("resize", onResize);
      observer.disconnect();
    };
  }, [measure]);

  const choose = (id: string, scroll = false) => {
    setSelected(id);
    if (scroll) {
      sentenceRefs.current[id]?.scrollIntoView({ block: "center", behavior: "smooth" });
    }
  };

  return (
    <main className="flex-1">
      <div ref={galleyRef} className="galley relative bg-stock text-ink">
        {leader && (
          <svg
            className="pointer-events-none absolute inset-0 hidden lg:block"
            width={leader.w}
            height={leader.h}
            viewBox={`0 0 ${leader.w} ${leader.h}`}
            aria-hidden="true"
          >
            <polyline
              key={selected}
              className="leader"
              points={leader.points}
              fill="none"
              stroke="var(--mark)"
              strokeWidth={1.5}
              strokeLinecap="square"
              pathLength={1}
            />
          </svg>
        )}

        <TrimMarks />

        <div className="mx-auto w-full max-w-[84rem] px-5 py-10 sm:px-8 lg:py-14 xl:px-16">
          <header className="grid max-w-[68rem] items-end gap-x-16 gap-y-9 lg:grid-cols-[minmax(0,1fr)_24rem]">
            <div>
              <h1 className="max-w-[18ch] text-[clamp(2.05rem,4.6vw,3.5rem)] font-bold leading-[1.02] tracking-[-0.03em] text-ink">
                Know what you&rsquo;re actually agreeing to.
              </h1>
              <p className="mt-5 max-w-[58ch] text-[1.05rem] leading-[1.5] text-ink-soft">
                Your client sent you a contract to sign. Redline tells you which terms
                will cost you and quotes the sentence each one came from, so you can
                find it in your own copy and ask for a change.
              </p>
              <div className="mt-7 flex flex-wrap items-center gap-x-6 gap-y-3">
                <a href="/sign-in" className={STAMP}>
                  Run your own contract
                </a>
                <span className="text-[0.85rem] text-ink-soft">
                  Freelance and contractor agreements.
                </span>
              </div>
            </div>

            <nav aria-labelledby="ranked">
              <h2 id="ranked" className={LABEL}>
                In this sample, worst first
              </h2>
              <ol className="mt-3 border-t border-rule">
                {flags.map((flag, i) => {
                  const active = selected === flag.id;
                  return (
                    <li key={flag.id} className="border-b border-rule">
                      <button
                        type="button"
                        onClick={() => choose(flag.id, true)}
                        aria-pressed={active}
                        className="flex w-full cursor-pointer items-start gap-3 py-2.5 text-left transition-colors duration-200 hover:bg-stock-shade"
                      >
                        <span
                          className={`numeric mt-px w-3 shrink-0 text-[0.78rem] font-bold ${
                            active ? "text-mark-deep" : "text-ink-soft"
                          }`}
                        >
                          {i + 1}
                        </span>
                        <span className="flex-1">
                          <span
                            className={`block text-[0.92rem] font-semibold leading-snug ${
                              active
                                ? "text-ink underline decoration-mark decoration-2 underline-offset-4"
                                : "text-ink-soft"
                            }`}
                          >
                            {flag.title}
                          </span>
                          <span className="mt-1.5 flex flex-wrap items-center gap-x-3 gap-y-1">
                            <SeverityMeter
                              steps={flag.severity}
                              word={flag.severityWord}
                            />
                            {flag.clauseReference && (
                              <span className="numeric font-document text-[0.82rem] text-ink-soft">
                                Clause {flag.clauseReference}
                              </span>
                            )}
                          </span>
                        </span>
                      </button>
                    </li>
                  );
                })}
              </ol>
            </nav>
          </header>

          <div className="mt-14 max-w-[64rem] border-t border-rule pt-8">
            <h2 className="text-[0.75rem] font-semibold uppercase tracking-[0.2em] text-ink-soft">
              What you get
            </h2>
            <ul className="mt-6 grid gap-x-12 gap-y-7 sm:grid-cols-3">
              {WHAT_YOU_GET.map(([name, note]) => (
                <li key={name} className="border-b border-rule pb-6">
                  <span className="block text-[0.95rem] font-semibold leading-snug text-ink">
                    {name}
                  </span>
                  <span className="mt-2 block text-[0.88rem] leading-relaxed text-ink-soft">
                    {note}
                  </span>
                </li>
              ))}
            </ul>
          </div>

          <div className="mt-14">
            <Masthead document={`Sample: ${fixture}`} law={LAW_READ_UNDER} state="Marked proof" />
          </div>
          <p className="mt-3 max-w-[68ch] text-[0.86rem] leading-relaxed text-ink-soft">
            {WHERE_THIS_CAME_FROM}
          </p>

          <div className="mt-9 space-y-9">
            {clauses.map((clause, index) => {
              const finding = flags.find((flag) => flag.id === clause.flagIds[0]);
              const active = finding?.id === selected;
              return (
                <div
                  key={index}
                  className={`grid max-w-[64rem] gap-x-10 gap-y-4 transition-opacity duration-500 lg:grid-cols-[minmax(0,1fr)_18rem] ${
                    active ? "opacity-100" : "opacity-[0.82]"
                  }`}
                >
                  <div>
                    {clause.heading && (
                      <h3 className="numeric font-document text-[1.02rem] font-bold text-ink">
                        {clause.heading}
                      </h3>
                    )}
                    <p className="mt-2 max-w-[58ch] whitespace-pre-line font-document text-[1.06rem] leading-[1.62] text-ink">
                      {clause.spans.map((span, i) => {
                        const marked = flags.find((flag) => flag.id === span.flagId);
                        if (!marked) {
                          return <span key={i}>{span.text}</span>;
                        }
                        const kind = markFor(marked.clauseType);
                        const isSelected = marked.id === selected;
                        return (
                          <span key={i}>
                            {/* The in-line half of the pair: proof correction marks the
                                text and the margin, and the two read together. */}
                            <ProofMark
                              kind={kind}
                              className="mr-0.5 inline h-[0.95em] w-[0.95em] -translate-y-[0.1em] align-middle text-mark"
                            />
                            <span
                              id={`sentence-${marked.id}`}
                              ref={(el) => {
                                sentenceRefs.current[marked.id] = el;
                              }}
                              className={`decoration-mark decoration-[1.5px] underline-offset-[5px] ${
                                kind === "strike"
                                  ? "line-through"
                                  : isSelected
                                    ? "underline"
                                    : "underline decoration-dotted"
                              } ${isSelected ? "bg-stock-shade" : ""}`}
                            >
                              {span.text}
                            </span>
                          </span>
                        );
                      })}
                    </p>
                  </div>

                  {finding && (
                    <div className="lg:border-l lg:border-rule lg:pl-7">
                      <button
                        type="button"
                        ref={(el) => {
                          markRefs.current[finding.id] = el;
                        }}
                        onClick={() => choose(finding.id)}
                        aria-pressed={active}
                        aria-controls={`sentence-${finding.id}`}
                        className="w-full cursor-pointer text-left transition-colors duration-200 hover:bg-stock-shade"
                      >
                        <span className="flex items-start gap-3 text-mark">
                          <ProofMark kind={markFor(finding.clauseType)} />
                          <span className="flex-1">
                            <span className="block text-[1rem] font-semibold leading-snug text-ink">
                              {finding.title}
                            </span>
                            <span className="mt-2 block">
                              <SeverityMeter
                                steps={finding.severity}
                                word={finding.severityWord}
                              />
                            </span>
                          </span>
                        </span>
                        <span className="sr-only">
                          {active ? "Showing" : "Show"} the sentence
                          {finding.clauseReference
                            ? ` in clause ${finding.clauseReference}`
                            : ""}{" "}
                          this came from
                        </span>
                      </button>
                      {active && (
                        <>
                          <p className="mt-4 max-w-[40ch] text-[0.94rem] leading-[1.55] text-ink-soft">
                            {finding.cost}
                          </p>
                          {/* A hedge names what the contract left out (`docs/adr/0006`).
                              It says what the mark was worked out from; it does not
                              lower the mark. */}
                          {finding.hedgeNote && (
                            <p className="mt-3 flex max-w-[40ch] items-start gap-2 border-t border-rule pt-3 text-[0.88rem] leading-[1.5] text-ink-soft">
                              <ProofMark kind="query" className="mt-0.5 h-4 w-4 text-mark" />
                              <span>{finding.hedgeNote}</span>
                            </p>
                          )}
                        </>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          <div className="mt-14 max-w-[64rem] border-t border-rule pt-8">
            <div className="flex flex-wrap items-baseline justify-between gap-x-8 gap-y-3">
              <h2 className="text-[0.75rem] font-semibold uppercase tracking-[0.2em] text-pencil">
                Checked, nothing to report
              </h2>
              <span className="numeric text-[0.7rem] font-semibold uppercase tracking-[0.2em] text-ink-soft">
                {cleared.length} of {checklistTotal} came back clean
              </span>
            </div>
            <p className="mt-3 max-w-[58ch] text-[0.94rem] leading-relaxed text-ink-soft">
              A line here means Redline read this contract on that point and found nothing
              worth taking up. Anything not on the list is either marked above, or
              something Redline could not settle from the wording.
            </p>
            <ul className="mt-6 grid max-w-[64rem] border-t border-rule sm:grid-cols-2 sm:gap-x-12">
              {cleared.map((entry) => (
                <li
                  key={entry.entry}
                  className="flex items-start gap-3 border-b border-rule py-3.5 text-[0.94rem] leading-[1.55] text-pencil"
                >
                  <ProofMark kind="check" className="mt-px h-5 w-5" />
                  <span>{entry.name}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="numeric mt-16 flex flex-wrap items-baseline justify-between gap-x-8 gap-y-2 border-t-2 border-ink pt-4 text-[0.68rem] font-semibold uppercase tracking-[0.2em] text-ink-soft">
            <span className="text-ink">Redline</span>
            <span>Read the margin, then the line it points to</span>
            <span>Sheet 1 of 1</span>
          </div>
        </div>
      </div>

      <div className="bg-field">
        <div className="mx-auto w-full max-w-[84rem] px-5 py-20 sm:px-8">
          <section aria-labelledby="limits">
            <h2
              id="limits"
              className="text-[clamp(1.6rem,3vw,2.2rem)] font-bold tracking-[-0.02em] text-field-ink"
            >
              What Redline will not do
            </h2>
            <dl className="mt-8 grid gap-x-12 gap-y-8 sm:grid-cols-2 lg:grid-cols-4">
              <div>
                <dt className="text-[1rem] font-semibold text-field-ink">
                  Tell you whether to sign
                </dt>
                <dd className="mt-2 text-[0.95rem] leading-relaxed text-field-soft">
                  It explains what the document says and drafts language you can send
                  back. The decision is yours, and it is not legal advice.
                </dd>
              </div>
              <div>
                <dt className="text-[1rem] font-semibold text-field-ink">
                  Read a scan or a photo
                </dt>
                <dd className="mt-2 text-[0.95rem] leading-relaxed text-field-soft">
                  If a file has no text in it, Redline says so instead of guessing. A
                  quote is worth nothing if the words behind it were misread.
                </dd>
              </div>
              <div>
                <dt className="text-[1rem] font-semibold text-field-ink">
                  Send your file anywhere
                </dt>
                <dd className="mt-2 text-[0.95rem] leading-relaxed text-field-soft">
                  Your document is read in your own browser. Only the text it contains is
                  stored, and only you can see it.
                </dd>
              </div>
              <div>
                <dt className="text-[1rem] font-semibold text-field-ink">
                  Cover every kind of document
                </dt>
                <dd className="mt-2 text-[0.95rem] leading-relaxed text-field-soft">
                  This version is built for freelance and contractor agreements. Leases
                  and terms of service are not in it.
                </dd>
              </div>
            </dl>
          </section>

          <section className="mt-20 border-t border-field-soft/30 pt-12">
            <p className="max-w-[38ch] text-[clamp(1.5rem,3.4vw,2.1rem)] font-bold leading-[1.12] tracking-[-0.02em] text-field-ink">
              You can still ask for a change. You just have to know what to ask for.
            </p>
            <a
              href="/sign-in"
              className="mt-8 inline-block cursor-pointer border-[3px] border-stock bg-mark-deep px-7 py-3.5 text-[0.82rem] font-bold uppercase tracking-[0.18em] text-stock transition-colors duration-200 hover:bg-stock hover:text-mark-deep focus-visible:bg-stock focus-visible:text-mark-deep"
            >
              Run your own contract
            </a>
          </section>

          <footer className="mt-20 flex flex-wrap items-baseline justify-between gap-x-10 gap-y-3 border-t border-field-soft/30 pt-6">
            <span className="font-document text-[1.05rem] italic text-field-ink">
              Redline
            </span>
            <span className="max-w-[58ch] text-[0.83rem] leading-relaxed text-field-soft">
              Redline explains a document and drafts language you can send. It does not
              tell you whether to sign, and it is not a law firm.
            </span>
          </footer>
        </div>
      </div>
    </main>
  );
}
